blank_issues_enabled: false
contact_links:
contact_links:
    - name: Bug report
      url: https://sample/url
      about: Reach out to support team
    - name: Feature Request
      url: https://sample/url
      about: Share ideas for new features
    - name: Ask a Question
      url: https://sample/url
      about: Ask the community for help