name: Test and Release Package

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org/'  # Set NPM registry

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Run tests
        run: pnpm test
				env: 
         FINTAVA_API_KEY: ${{ secrets.FINATAVA_API_KEY }}

  release:
    needs: test  # Only run if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create version bump
        run: |
          pnpx changeset version  # Bumps version according to changesets
          pnpm install  # Reinstall after version bump to update lockfile

      - name: Push version update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Version bump from changesets"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: |
          pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          FINTAVA_API_KEY: ${{ secrets.FINATAVA_API_KEY }}