name: Test and Release Package

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test
        env:
          FINTAVA_API_KEY: ${{ secrets.FINTAVA_API_KEY }}  # Adding API key for tests

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create version and test publish
        run: |
          pnpm changeset version
          pnpm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Your NPM token for publishing
          FINTAVA_API_KEY: ${{ secrets.FINTAVA_API_KEY }}  # API key for creating the client in the release process

      - name: Verify release
        run: echo "Dry run completed successfully."
